### ISSUE TITLE
順位処理を作る

### ISSUE THREAD

**Issue by NagasawaYuusei** [NagasawaYuusei/networkbattlerun#4]
現状、x座標が高いプレイヤーが先頭ということになっていますが、実際のマップはループするマップなので、先頭にいるプレイヤーのx座標が低い場合もあります。(左に進む場合など)
この順位処理を作っていただきたいです。
6/29まで

**Comment by MutoAyumu** [comment]
先頭がどのプレイヤーなのかを判定する
