### ISSUE TITLE
途中抜け時の処理

### ISSUE THREAD

**Issue by NagasawaYuusei** [NagasawaYuusei/networkbattlerun#8]
現状ゲーム中ゲームを終了すると、一位が抜けると、抜けた場所でカメラが固定され、１位が消えます。
ですので、これを１位が途中抜けした際、2位の人が1位になり、また、その際１人だけになったら、残った人を勝者としたいです。

**Comment by MutoAyumu** [comment]
今できている部分
先頭の人が途中抜けすると、次に先頭の人にカメラを向ける
ゲーム中のランキング（先頭から順）の変数はできている

出来てないこと
ゲームが終了する
